timezone: Europe/Berlin
exclude:
  - jekyll
show_drafts: true

monate: [Januar,Februar,März,April,Mai,Juni,Juli,August,September,Oktober,November,Dezember]
wt: [Mo,Di,Mi,Do,Fr,Sa,So]

defaults:
  -
    scope:
      path: ""
    values:
      layout: post
      author: Ber
      location: Jena
      category: None
      tags: untagged

