#!/bin/bash

export JEKYLL_VERSION=3.8
docker run \
    --name=jekyll \
    --volume="$(pwd)":/srv/jekyll \
    --rm \
    -it \
    -p 127.0.0.1:4000:4000 \
    jekyll/jekyll:$JEKYLL_VERSION \
    jekyll $@